### ISSUE TITLE
How to distinguish data-dependence edges from control-dependence edges?

### ISSUE THREAD

**Issue by for-just-we** [deeppda-icse23/DeepPDA#2]
Hi author, I recently run your tool and it's a inspiring work, but after using `MLP_pdg` to predict program dependence edges for statement sequence. How do I know which parts of the predictions are data-dependence edges?

**Comment by aashishyadavally** [comment]
Thank you for your interest :)
Based on our use cases, in the current version, we don't explicitly distinguish between control and data-dependence edges, though we did observe that the model learns both types of dependencies.
